export const projects = [
  {
    id: 1,
    title: "BookShelf",
    slug: "book-shelf",
    short_description:
      "BookShelf is a modern full-stack web application that revolutionizes the way people discover, purchase, and manage digital books.",
    descriptioin:
      "BookShelf is a modern full-stack web application that revolutionizes the way people discover, purchase, and manage digital books. The platform provides a seamless experience for readers, authors, and administrators with features including user authentication, book listings, shopping cart functionality, wishlist management, reviews and ratings system, AI-powered chatbot assistance, and comprehensive admin dashboard.",
    techStack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "NodeMailer",
      "JWT",
      "GROQ SDK",
      "Firebase",
      "Tailwind CSS",
    ],
    features: [
      "User registration and secure JWT authentication",

      "Book browsing with advanced filters (category, price, search)",

      "Shopping cart and secure checkout process",

      "Personal wishlist and reading history",

      "Book reviews and star ratings system",

      "AI-powered chatbot for book recommendations",

      "Author dashboard for book management",

      "Admin panel for complete platform control",

      "Email notifications via Nodemailer",

      "Google social login integration",

      "Real-time chat history storage",
    ],
    challenges: [
      "Authentication & Authorization System",
      "Real-time AI Chatbot Integration",
      "Image Upload & Cloudinary Integration",
      "Shopping Cart & Wishlist Synchronization",
      "Responsive Admin Dashboard",
      "Email System with Nodemailer",
      "Database Schema Design",
      "Search & Filter Performance",
    ],
    learnings: [
      "Next.js App Router Mastery",
      "JWT Authentication Best Practices",
      "MongoDB Aggregation & Indexing",
      "Cloudinary Image Management",
      "AI Integration with Groq API",
      "Real-time UI Updates",
      "Error Handling & User Feedback",
      "Responsive Design Patterns",
    ],
    futurePlans: [
      "Add personalized book recommendations based on reading and purchase history",
      "Introduce author analytics, subscription plans, and advanced review moderation",
      "Improve search performance with richer filters and indexed full-text search",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://client-bookshelf.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/BookShelf",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/tgyxgqPR/Screenshot-from-2026-04-28-19-42-08.png",
      "https://i.postimg.cc/fLPyYD3G/Screenshot-from-2026-04-28-19-42-15.png",
      "https://i.postimg.cc/rwT1DN2q/Screenshot-from-2026-04-28-19-42-22.png",
      "https://i.postimg.cc/gc684TYd/Screenshot-from-2026-04-28-19-42-30.png",
      "https://i.postimg.cc/4yCKrXJC/Screenshot-from-2026-04-28-19-42-37.png",
      "https://i.postimg.cc/t4R10SHJ/Screenshot-from-2026-04-28-19-43-14.png",
      "https://i.postimg.cc/5Nbyv7jb/Screenshot-from-2026-04-28-19-43-28.png",
      "https://i.postimg.cc/pVYX2fCQ/Screenshot-from-2026-04-28-19-43-48.png",
      "https://i.postimg.cc/zvJNLQ7M/Screenshot-from-2026-04-28-19-43-56.png",
      "https://i.postimg.cc/Xq2RrYXR/Screenshot-from-2026-04-28-19-44-01.png",
      "https://i.postimg.cc/zvfMYY0r/Screenshot-from-2026-04-28-19-44-08.png",
      "https://i.postimg.cc/tJfr0Zsq/Screenshot-from-2026-04-28-19-44-14.png",
      "https://i.postimg.cc/wxPFjNB7/Screenshot-from-2026-04-28-19-44-22.png",
      "https://i.postimg.cc/yW4FXFgC/Screenshot-from-2026-04-28-19-44-30.png",
    ],
  },
  {
    id: 2,
    title: "BD BOOK",
    slug: "bd-book",
    short_description:
      "A social media platform for Bangladeshi people to share their thoughts and ideas.",
    descriptioin:
      "BD BOOK is a social media platform designed specifically for Bangladeshi people to share their thoughts and ideas. It offers a wide range of features, including posting, commenting, liking, sharing, video calls, audio calls, meetings, and more. The platform is powered by AI and ML technologies, which enable it to provide personalized content recommendations and enhance user engagement through a sophisticated algorithm. Which is also powered by AI and ML.And it has a large algorithm for user engagement and content recommendation. The platform is built with a focus on security and privacy, ensuring that users' data is protected at all times. With its responsive design and user-friendly interface, BD BOOK provides an enjoyable and seamless experience for users to connect and share their ideas with others.",
    techStack: [
      "Next.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
    ],
    features: [
      "Full stack social media platform",
      "AI and ML-powered content recommendation",
      "Real-time communication with video and audio calls",
      "User engagement algorithm",
      "Responsive design with Tailwind CSS",
      "Secure authentication and authorization",
      "Scalable architecture with Node.js and MongoDB",
      "and many more!",
    ],
    challenges: [
      "Implementing real-time communication features",
      "Designing a scalable architecture to handle a large user base",
      "Integrating AI and ML technologies for content recommendation",
      "Ensuring data security and privacy for users",
      "Creating a user-friendly interface with Tailwind CSS",
    ],
    learnings: [
      "Gained experience in full stack development with Next.js, Node.js, and MongoDB",
      "Learned how to implement real-time communication features using Socket.io",
      "Gained insights into AI and ML technologies for content recommendation",
      "Learned about data security and privacy best practices",
      "Improved skills in responsive design with Tailwind CSS",
    ],
    futurePlans: [
      "Improve the recommendation engine with safer and more relevant personalized feeds",
      "Add stronger content moderation, reporting tools, and privacy controls",
      "Optimize real-time calls and messaging for larger concurrent audiences",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://client-bdbook.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/BD-Book",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/ZKBnq0P9/Screenshot-2026-04-08-161518.png",
      "https://i.postimg.cc/1zP3MHkN/Screenshot-2026-04-08-161606.png",
      "https://i.postimg.cc/0N897NSy/Screenshot-2026-04-08-161616.png",
      "https://i.postimg.cc/0jJv9KgP/Screenshot-2026-04-08-161625.png",
      "https://i.postimg.cc/0jJv9KgP/Screenshot-2026-04-08-161625.png",
      "https://i.postimg.cc/nVQMFCYy/Screenshot-2026-04-08-161639.png",
    ],
  },
  {
    id: 3,
    title: "Career Crafter",
    slug: "career-crafter",
    short_description:
      "Career Crafter is a career guidance platform that helps individuals explore and plan their career paths.",
    descriptioin:
      "Career Crafter is an AI powered career guidance platform that helps individuals explore and plan their career paths. The platform offers a wide range of features, including personalized career assessments, job search tools, resume building, interview preparation, and more. With its user-friendly interface and comprehensive resources, Career Crafter empowers users to make informed decisions about their careers and achieve their professional goals.",
    techStack: [
      "React.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
    ],
    features: [
      "AI Powered career guidance",
      "AI Assistant for career advice",
      "AI Quick job search",
      "AI tools for quick preparation",
      "Personalized career assessments",
      "Job search tools",
      "Resume building",
      "Interview preparation",
      "User-friendly interface",
      "Comprehensive resources",
      "and many more!",
    ],
    challenges: [
      "Designing a platform that provides accurate career guidance",
      "Creating a user-friendly interface that caters to diverse user needs",
      "Integrating various features seamlessly into a single platform",
    ],
    learnings: [
      "Gained experience in creating career guidance platforms",
      "Learned about the importance of personalized recommendations in career development",
      "Improved skills in building user-friendly interfaces with Next.js and Tailwind CSS",
    ],
    futurePlans: [
      "Add AI-assisted career roadmaps that adapt to each user's goals and progress",
      "Integrate verified job listings and application tracking",
      "Expand resume analysis and mock interview feedback with measurable scoring",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://careercrafter5.web.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/Career-Crafter",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/Kv5dThPt/Screenshot-2026-04-08-170546.png",
      "https://i.postimg.cc/zDCMmYPR/Screenshot-2026-04-08-170557.png",
      "https://i.postimg.cc/x85tXYWW/Screenshot-2026-04-08-170645.png",
      "https://i.postimg.cc/Wbp5QFZD/Screenshot-2026-04-08-170702.png",
      "https://i.postimg.cc/13fJ3kJR/Screenshot-2026-04-08-170714.png",
      "https://i.postimg.cc/25WG4ns0/Screenshot-2026-04-08-170732.png",
      "https://i.postimg.cc/hjb0YcPz/Screenshot-2026-04-08-170747.png",
      "https://i.postimg.cc/SRgfyd9z/Screenshot-2026-04-08-170808.png",
      "https://i.postimg.cc/MpMmSypn/Screenshot-2026-04-08-170819.png",
    ],
  },
  {
    id: 4,
    title: "Code Circle",
    slug: "code-circle",
    short_description:
      "Code Circle is a collaborative coding platform that allows developers to work together on coding projects in real-time.",
    descriptioin:
      "Code Circle is a collaborative coding platform that allows developers to work together on coding projects in real-time. The platform offers features such as code sharing, live collaboration, and integrated development tools. With its user-friendly interface and powerful collaboration capabilities, Code Circle enables developers to enhance their productivity and foster teamwork in coding projects.",
    techStack: [
      "React.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
    ],
    features: [
      "Real-time collaborative coding",
      "Code sharing",
      "Integrated development tools",
      "User-friendly interface",
      "Powerful collaboration capabilities",
    ],
    challenges: [
      "Designing a platform that facilitates seamless real-time collaboration",
      "Creating a user-friendly interface that caters to diverse user needs",
      "Integrating various development tools into a single platform",
    ],
    learnings: [
      "Gained experience in building collaborative coding platforms",
      "Learned about the importance of real-time features in developer tools",
      "Improved skills in creating user-friendly interfaces with React.js and Tailwind CSS",
    ],
    futurePlans: [
      "Add collaborative code execution with isolated and secure environments",
      "Introduce project rooms, version history, and team permission controls",
      "Improve editor performance and support more programming languages",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://codecircle5.web.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/Code-Circle",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/zGb6cHmj/Screenshot-2026-04-08-171626.png",
      "https://i.postimg.cc/rmJPrS4G/Screenshot-2026-04-08-171652.png",
      "https://i.postimg.cc/j2SkQLQz/Screenshot-2026-04-08-171731.png",
      "https://i.postimg.cc/gcg7cHmw/Screenshot-2026-04-08-171747.png",
      "https://i.postimg.cc/52CK3cvq/Screenshot-2026-04-08-171800.png",
      "https://i.postimg.cc/0NGtTpV7/Screenshot-2026-04-08-171814.png",
      "https://i.postimg.cc/vTKXrXZ0/Screenshot-2026-04-08-171833.png",
    ],
  },
  {
    id: 5,
    title: "Coursion",
    slug: "coursion",
    short_description:
      "Coursion is an online learning platform that offers a wide range of courses and resources for learners of all levels.",
    descriptioin:
      "Coursion is an online learning platform that offers a wide range of courses and resources for learners of all levels. The platform provides features such as personalized course recommendations, interactive learning materials, and a supportive community. With its user-friendly interface and comprehensive course offerings, Coursion empowers learners to acquire new skills and knowledge effectively.",
    techStack: ["React.js", "Tailwind CSS", "Node.js", "Express.js", "MongoDB"],
    features: [
      "Personalized course recommendations",
      "Interactive learning materials",
      "Supportive community",
      "User-friendly interface",
      "Comprehensive course offerings",
    ],
    challenges: [
      "Designing a platform that provides personalized course recommendations",
      "Creating interactive learning materials that engage users",
      "Building a supportive community for learners",
    ],
    learnings: [
      "Gained experience in building online learning platforms",
      "Learned about the importance of personalized recommendations in education",
      "Improved skills in creating engaging learning materials with React.js and Tailwind CSS",
    ],
    futurePlans: [
      "Add progress tracking, certificates, quizzes, and instructor analytics",
      "Introduce personalized learning paths based on skills and completed lessons",
      "Improve accessibility and support downloadable lessons for low-connectivity users",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://coursion-9faf6.web.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/Coursion",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/J03ZnqBy/Screenshot-2026-04-08-172214.png",
      "https://i.postimg.cc/rwwxV5y6/Screenshot-2026-04-08-172229.png",
      "https://i.postimg.cc/25PZ7JQL/Screenshot-2026-04-08-172243.png",
      "https://i.postimg.cc/Hnm8fyPT/Screenshot-2026-04-08-172257.png",
      "https://i.postimg.cc/1R0qDvfP/Screenshot-2026-04-08-172308.png",
    ],
  },
  {
    id: 6,
    title: "School and college management",
    slug: "school-college-management",
    short_description:
      "A school and college management system that helps educational institutions manage their operations efficiently.",
    descriptioin:
      "A school and college management system that helps educational institutions manage their operations efficiently. The platform offers features such as student enrollment, attendance tracking, grade management, and communication tools for teachers, students, and parents. With its user-friendly interface and comprehensive features, the system streamlines administrative tasks and enhances communication within the educational community.",
    techStack: ["React.js", "Tailwind CSS", "Node.js", "Express.js", "MongoDB"],
    features: [
      "Student enrollment",
      "Attendance tracking",
      "Grade management",
      "Communication tools for teachers, students, and parents",
      "User-friendly interface",
      "Comprehensive features for educational institutions",
    ],
    challenges: [
      "Designing a platform that meets the needs of educational institutions",
      "Creating a user-friendly interface for diverse users",
      "Integrating various features seamlessly into a single platform",
    ],
    learnings: [
      "Gained experience in building management systems for educational institutions",
    ],
    futurePlans: [
      "Add automated attendance, exam result publishing, and guardian notifications",
      "Introduce role-specific dashboards for students, teachers, parents, and administrators",
      "Provide downloadable academic reports and institution-level analytics",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://school.moshiurrahman.online/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/School-and-college-management",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/hPkRg11J/Screenshot-2026-04-08-172645.png",
      "https://i.postimg.cc/tJs8Gs1L/Screenshot-2026-04-08-172715.png",
      "https://i.postimg.cc/xTbBsbVR/Screenshot-2026-04-08-172738.png",
    ],
  },
  {
    id: 7,
    title: "Netrakona Pressclub website",
    slug: "netrakona-pressclub-website",
    short_description:
      "Netrakona Pressclub website is a platform that provides news and information about Netrakona district.",
    descriptioin:
      "Netrakona Pressclub website is a platform that provides news and information about Netrakona district. The website offers features such as news articles, event updates, and a directory of local businesses and organizations. With its user-friendly interface and comprehensive content, the website serves as a valuable resource for residents and visitors of Netrakona.",
    techStack: ["React.js", "Tailwind CSS", "Node.js", "Express.js", "MongoDB"],
    features: [
      "News articles about Netrakona district",
      "Event updates for the local community",
      "Directory of local businesses and organizations",
      "User-friendly interface",
      "Comprehensive content for residents and visitors",
    ],
    challenges: [
      "Designing a platform that effectively serves the local community",
      "Creating a user-friendly interface for diverse users",
      "Integrating various features seamlessly into a single platform",
    ],
    learnings: ["Gained experience in building websites for local communities"],
    futurePlans: [
      "Add a searchable digital archive for local news and press releases",
      "Introduce reporter profiles, editorial approval workflows, and breaking-news notifications",
      "Improve local event coverage and accessibility for readers on slower networks",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://pressclub-netrakona-client.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/Pressclub-client",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/YSkZ81gr/Screenshot-2026-04-08-201538.png",
    ],
  },
  {
    id: 8,
    title: "Service Provider",
    slug: "service-provider",
    short_description:
      "Service Provider is a platform that connects service providers with customers in need of their services.",
    descriptioin:
      "Service Provider is a platform that connects service providers with customers in need of their services. The platform offers features such as service listings, customer reviews, and a secure payment system. With its user-friendly interface and comprehensive features, Service Provider facilitates seamless interactions between service providers and customers, making it easier for users to find and access the services they need.",
    techStack: ["React.js", "Tailwind CSS", "Node.js", "Express.js", "MongoDB"],
    features: [
      "Service listings for various types of services",
      "custom dashboard for service providers to manage their listings and interactions with customers",
      "Customer reviews and ratings",
      "Secure payment system for transactions",
      "User-friendly interface",
      "Comprehensive features for service providers and customers",
    ],
    challenges: [
      "Designing a platform that effectively connects service providers with customers",
      "Creating a user-friendly interface for diverse users",
      "Integrating various features seamlessly into a single platform",
    ],
    learnings: [
      "Gained experience in building platforms for service providers and customers",
    ],
    futurePlans: [
      "Add provider verification, service-area mapping, and transparent customer reviews",
      "Introduce secure online payments, booking schedules, and automated reminders",
      "Build recommendation and dispute-resolution features to improve marketplace trust",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://projuktisheba.moshiurrahman.online/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/projukti-sheba",
      },
    ],
    screenshots: [
      "https://i.postimg.cc/j5RWskfs/Screenshot-2026-04-08-202056.png",
      "https://i.postimg.cc/kX22XS2q/Screenshot-2026-04-08-202116.png",
      "https://i.postimg.cc/V64F1tdT/Screenshot-2026-04-08-202128.png",
      "https://i.postimg.cc/T14q5Xjr/Screenshot-2026-04-08-202139.png",
      "https://i.postimg.cc/TYBJRfY7/Screenshot-2026-04-08-202153.png",
      "https://i.postimg.cc/q7xsXKXT/Screenshot-2026-04-08-202208.png",
      "https://i.postimg.cc/4NHp2qbQ/Screenshot-2026-04-08-202220.png",
      "https://i.postimg.cc/HxLywhks/Screenshot-2026-04-08-202233.png",
    ],
  },
  {
    id: 9,
    title: "docAppoint",
    slug: "doc-appoint",
    short_description:
      "docAppoint is a smart healthcare booking platform for finding doctors and managing appointments online.",
    descriptioin:
      "docAppoint helps patients browse verified doctors, view doctor details, book appointments, and manage their healthcare journey through a secure and user-friendly platform.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "MongoDB",
      "Better Auth",
      "Axios",
    ],
    features: [
      "Secure email/password and Google authentication",
      "Browse and search verified doctors",
      "Doctor details and availability pages",
      "Online appointment booking",
      "Patient dashboard and profile management",
      "Appointment update and cancellation flow",
    ],
    challenges: [
      "Implementing secure authentication with protected routes",
      "Building a smooth doctor discovery and booking flow",
      "Managing appointment data across patient-facing pages",
    ],
    learnings: [
      "Better Auth integration with MongoDB",
      "Next.js App Router and protected routing",
      "Building responsive healthcare booking interfaces",
    ],
    futurePlans: [
      "Add doctor-side appointment management and availability controls",
      "Introduce email reminders and appointment notifications",
      "Add prescription and medical history management features",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://doc-appoint-client-siam-17.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/doc-appoint-client-siam-17",
      },
    ],
    screenshots: [
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/",
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/about",
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/doctors",
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/v1/dashboard",
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/v1/dashboard/profile",
      "https://image.thum.io/get/width/1920/crop/1080/https://doc-appoint-client-siam-17.vercel.app/v1/dashboard/bookings",
    ],
  },
  {
    id: 10,
    title: "Tech Bazaar",
    slug: "tech-bazaar",
    short_description:
      "Tech Bazaar is a role-based marketplace for discovering products, selling online, and making secure payments.",
    descriptioin:
      "Tech Bazaar brings buyers, sellers, and admins into one responsive marketplace. Buyers can browse and purchase approved products, sellers can manage products and plans, and admins can moderate accounts, products, and payments.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "MongoDB",
      "Better Auth",
      "Stripe",
      "HeroUI",
      "Framer Motion",
      "ImgBB",
    ],
    features: [
      "Role-based buyer, seller, and admin dashboards",
      "Product search, category filters, sorting, and pagination",
      "Stripe Checkout with payment history",
      "Seller product, sales, revenue, and plan management",
      "Admin account and product moderation",
      "Protected routes and profile management",
      "Responsive UI with toast feedback and animations",
    ],
    challenges: [
      "Designing separate workflows for three user roles",
      "Integrating secure Stripe payment and confirmation flows",
      "Keeping product moderation and marketplace data consistent",
    ],
    learnings: [
      "Role-based access control with Better Auth",
      "Stripe Checkout and payment record integration",
      "Building a complete marketplace workflow with Next.js",
    ],
    futurePlans: [
      "Add product reviews, wishlists, and order tracking",
      "Introduce seller analytics and promotional campaigns",
      "Improve marketplace recommendations and notification features",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://tech-bazar-client.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/tech-Bazaar-client",
      },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28477%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28478%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28479%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28480%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28481%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28482%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28483%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/tech-Bazaar-client/main/public/images/Screenshot%20%28484%29.png",
    ],
  },
  {
    id: 11,
    title: "HireLoop",
    slug: "hireloop",
    short_description:
      "HireLoop is a role-based job platform connecting job seekers, recruiters, and administrators.",
    descriptioin:
      "HireLoop makes job searching and hiring easier with job discovery, saved jobs, applications, company and job management, role-based dashboards, subscription plans, and Stripe payments.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "MongoDB",
      "Better Auth",
      "Stripe",
      "HeroUI",
      "Motion",
      "ImgBB",
    ],
    features: [
      "Job seeker, recruiter, and admin roles",
      "Job search with filters and detailed job pages",
      "Saved jobs and application tracking",
      "Recruiter company and job post management",
      "Admin user, company, job, and payment controls",
      "Free, Pro, Premium, Growth, and Enterprise plans",
      "Stripe checkout with subscription history",
      "Protected routes and account approval system",
    ],
    challenges: [
      "Designing separate role-based experiences for three user types",
      "Managing subscription limits and protected dashboard access",
      "Connecting applications, job posts, company approval, and payments",
    ],
    learnings: [
      "Role-based access control with Better Auth",
      "Stripe subscription and payment lifecycle integration",
      "Building scalable job seeker and recruiter dashboards",
    ],
    futurePlans: [
      "Add AI-powered job matching and resume recommendations",
      "Introduce recruiter interview scheduling and email notifications",
      "Improve analytics for applications, hiring, and subscription growth",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://hireloop-client-six.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/hireloop-client",
      },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28173%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28174%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28175%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28176%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28177%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28178%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28179%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28180%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28181%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/hireloop-client/main/public/photos/Screenshot%20%28182%29.png",
    ],
  }
  ,{
    id: 12,
    title: "FundHorizon",
    slug: "fund-horizon",
    short_description:
      "FundHorizon is a role-based crowdfunding platform connecting creators with supporters for meaningful projects.",
    descriptioin:
      "The platform supports campaign discovery, credit-based contributions, creator campaign management, admin moderation, Stripe credit purchases, notifications, reports, and withdrawal workflows.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "MongoDB",
      "JWT Authentication",
      "Stripe",
      "ImgBB",
      "Recharts",
      "Swiper",
    ],
    features: [
      "Supporter, creator, and admin role-based dashboards",
      "Campaign search, filtering, sorting, and detail pages",
      "Credit purchase and contribution workflow with Stripe",
      "Creator campaign creation, updates, approvals, and withdrawals",
      "Admin user, campaign, contribution, report, and withdrawal management",
      "Notifications for approvals, contributions, and platform activity",
      "Protected routes with persistent authenticated sessions",
      "Responsive campaign cards, charts, forms, and dashboard layouts",
    ],
    challenges: [
      "Coordinating three role-specific workflows across one platform",
      "Maintaining accurate credit balances during contributions, refunds, and purchases",
      "Building a trustworthy moderation and withdrawal process for crowdfunding data",
    ],
    learnings: [
      "Designing secure role-based authorization for full-stack applications",
      "Connecting Stripe payments with internal credit and transaction records",
      "Creating transparent dashboards for campaign, contribution, and payout tracking",
    ],
    futurePlans: [
      "Add campaign comments, creator updates, and richer supporter engagement",
      "Introduce automated email notifications and campaign analytics",
      "Improve fraud detection, reporting, and payout verification workflows",
    ],
    links: [
      {
        name: "Live Demo",
        url: "https://fund-horizon-client.vercel.app/",
      },
      {
        name: "GitHub",
        url: "https://github.com/Khalid-Sifullah-Siam/FundHorizon-Client",
      },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28426%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28427%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28428%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28429%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28430%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28431%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28432%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28433%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28434%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28435%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28436%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/FundHorizon-Client/main/public/images/Screenshot%20%28437%29.png",
    ],
  },
  {
    id: 13,
    title: "ArtBro",
    slug: "artbro",
    short_description:
      "ArtBro is a multi-role art marketplace connecting independent artists with art lovers.",
    descriptioin:
      "Users can discover and purchase original artwork, artists can manage listings and sales, and administrators can oversee users, artwork, transactions, and analytics.",
    techStack: ["Next.js", "React", "Tailwind CSS", "MongoDB", "Better Auth", "JWT", "Stripe", "ImgBB", "Framer Motion", "GSAP"],
    features: [
      "Artwork browsing with search, filters, sorting, and pagination",
      "Artwork detail pages with purchase and comment flows",
      "User purchase history and profile management",
      "Artist artwork CRUD, image upload, and sales history",
      "Admin user, role, artwork, transaction, and analytics management",
      "Email/password and Google authentication",
      "Stripe checkout and subscription upgrade flow",
      "Responsive layouts with mobile navigation and custom system pages",
    ],
    challenges: [
      "Designing separate marketplace experiences for users, artists, and admins",
      "Connecting artwork purchases, comments, sales history, and Stripe transactions",
      "Keeping protected dashboards and role-based redirects consistent",
    ],
    learnings: [
      "Building role-based art marketplace workflows",
      "Integrating Stripe checkout with purchase and transaction history",
      "Combining reusable responsive UI with Framer Motion and GSAP",
    ],
    futurePlans: [
      "Add wishlist, artist follow, and richer artwork discovery features",
      "Introduce reviews, recommendations, and artist analytics",
      "Improve moderation, inventory, and order fulfillment workflows",
    ],
    links: [
      { name: "Live Demo", url: "https://art-bro-client.vercel.app/" },
      { name: "GitHub", url: "https://github.com/Khalid-Sifullah-Siam/ArtBro-client" },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28135%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28136%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28137%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28138%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28139%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28140%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28141%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28142%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28143%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28144%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28145%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28146%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28147%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28148%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28149%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28150%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/ArtBro-client/main/public/images/Screenshot%20%28151%29.png",
    ],
  },
  {
    id: 14,
    title: "Ticketo",
    slug: "ticketo",
    short_description:
      "Ticketo is a role-based event platform where attendees book tickets, organizers manage events, and admins oversee the marketplace.",
    descriptioin:
      "Users can discover approved events, purchase tickets through Stripe, and manage their profiles, while organizers run events and admins moderate users, submissions, and transactions.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "HeroUI",
      "Framer Motion",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Better Auth",
      "Stripe",
      "ImgBB",
    ],
    features: [
      "Event browsing with details, filters, and approved-event discovery",
      "Stripe ticket booking with payment success and saved ticket history",
      "Attendee ticket, payment history, and profile management",
      "Organizer organization profile and event CRUD workflows",
      "Event banner and organization logo image uploads",
      "Attendee information and organizer dashboard tools",
      "Admin role management, event moderation, and transaction monitoring",
      "Responsive layouts for desktop and mobile devices",
    ],
    challenges: [
      "Designing separate attendee, organizer, and admin experiences",
      "Connecting ticket booking, Stripe payments, and saved ticket history",
      "Keeping event approval, role protection, and dashboard access consistent",
    ],
    learnings: [
      "Building role-based event booking and management workflows",
      "Integrating Stripe checkout with ticket and payment records",
      "Creating responsive dashboards with reusable UI components",
    ],
    futurePlans: [
      "Add ticket QR codes and event check-in functionality",
      "Introduce event reminders, reviews, and organizer analytics",
      "Improve discovery with recommendations and richer event filtering",
    ],
    links: [
      { name: "Live Demo", url: "https://ticketo-client-v5k4.vercel.app/" },
      { name: "GitHub", url: "https://github.com/Khalid-Sifullah-Siam/Ticketo-client" },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28244%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28245%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28246%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28247%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28248%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28249%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28250%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28251%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28252%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28253%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28254%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28255%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28256%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28257%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28258%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28259%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28260%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28261%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28262%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28263%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/Ticketo-client/main/public/images/Screenshot%20%28264%29.png",
    ],
  },
  {
    id: 15,
    title: "Wanderlast",
    slug: "wanderlast",
    short_description:
      "Wanderlast is a modern travel booking platform for discovering destinations, booking trips, and managing travel plans.",
    descriptioin:
      "Users can explore destinations, search and sort travel options, book trips, and manage their profiles and booking history through a secure, responsive travel experience.",
    techStack: [
      "Next.js 16",
      "React 19",
      "Tailwind CSS",
      "HeroUI",
      "Framer Motion",
      "Lucide Icons",
      "MongoDB",
      "Better Auth",
      "Context API",
      "React Toastify",
    ],
    features: [
      "Destination discovery with detailed travel information",
      "Live search and A-Z/Z-A sorting for destinations and bookings",
      "Trip booking and personal itinerary management",
      "User profile with travel and booking history",
      "Email/password authentication with Google OAuth",
      "Protected user routes with Better Auth sessions",
      "Polished loading states with animated feedback",
      "Responsive layouts for desktop, tablet, and mobile devices",
    ],
    challenges: [
      "Building a secure Better Auth flow with a MongoDB adapter",
      "Creating smooth destination search, sorting, and booking workflows",
      "Maintaining responsive UI and consistent loading states across protected pages",
    ],
    learnings: [
      "Working with the Next.js App Router and API routes",
      "Implementing Google OAuth and protected user sessions",
      "Using Tailwind CSS v4 with reusable responsive components",
    ],
    futurePlans: [
      "Add destination ratings and real-time reviews",
      "Introduce wishlist functionality for future trips",
      "Integrate direct booking payments and AI travel recommendations",
    ],
    links: [
      { name: "Live Demo", url: "https://wanderlast-client-hazel.vercel.app/" },
      { name: "GitHub", url: "https://github.com/Khalid-Sifullah-Siam/wanderlast-client" },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2841%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2842%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2843%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2844%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2845%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2846%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2847%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2848%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2849%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2850%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2851%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2852%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/wanderlast-client/main/public/ReadmeImages/Screenshot%20%2853%29.png",
    ],
  },
  {
    id: 16,
    title: "English Janala",
    slug: "english-janala",
    short_description:
      "English Janala is a responsive vocabulary learning platform for exploring lessons, learning words, and improving pronunciation.",
    descriptioin:
      "Learners can browse lesson-based vocabulary, search words, open detailed definitions, listen to pronunciations, and practice through a clean responsive interface.",
    techStack: [
      "HTML5",
      "Tailwind CSS",
      "DaisyUI",
      "Vanilla JavaScript",
      "Web Speech API",
      "Programming Hero Open API",
    ],
    features: [
      "Dynamic lesson buttons loaded from the vocabulary API",
      "Vocabulary cards filtered by selected lesson",
      "Global search across available words",
      "Word details modal with meaning, example, pronunciation, and synonyms",
      "Text-to-speech pronunciation using the Web Speech API",
      "Loading spinner and empty-state handling",
      "Active lesson highlighting for clear navigation",
      "Responsive layout with FAQ accordion",
    ],
    challenges: [
      "Managing asynchronous API requests while keeping the interface responsive",
      "Handling empty lessons and missing vocabulary data gracefully",
      "Organizing filtering, word details, pronunciation, and search in vanilla JavaScript",
    ],
    learnings: [
      "Building a data-driven interface with fetch and DOM manipulation",
      "Improving UX with loading states, modal details, and active controls",
      "Using the Web Speech API to add practical pronunciation support",
    ],
    futurePlans: [
      "Add saved words and favorite vocabulary collections",
      "Improve search with instant filtering or debounced input",
      "Add user progress tracking and lesson completion features",
    ],
    links: [
      { name: "Live Demo", url: "https://khalid-sifullah-siam.github.io/English-Janala" },
      { name: "GitHub", url: "https://github.com/Khalid-Sifullah-Siam/English-Janala" },
    ],
    screenshots: [
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2874%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2875%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2876%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2877%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2878%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2879%29.png",
      "https://raw.githubusercontent.com/Khalid-Sifullah-Siam/English-Janala/main/assets/Images/Screenshot%20%2880%29.png",
    ],
  },
];
